
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-app
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-app
    spec:
      containers:
      - image: registry.gitlab.com/danlos44/gitlab-crud/my-image
        name: mongo-app
        ports:
        - containerPort: 5000
    
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-app
  ports:
  - name: app-port
    port: 5000
    targetPort: 5000
  type: LoadBalancer











